"""add tablename

Revision ID: 4037b1420e0c
Revises: 38e5246c05cc
Create Date: 2024-05-27 14:40:46.717025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4037b1420e0c'
down_revision = '38e5246c05cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=True),
    sa.Column('invitee_user_id', sa.Integer(), nullable=True),
    sa.Column('date_of_invate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inviter_user_id', sa.INTEGER(), nullable=True),
    sa.Column('invitee_user_id', sa.INTEGER(), nullable=True),
    sa.Column('date_of_invate', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invates')
    # ### end Alembic commands ###
