"""added session

Revision ID: 47380682aa83
Revises: 70f672798730
Create Date: 2024-05-24 12:15:55.618535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47380682aa83'
down_revision = '70f672798730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_of_creation', sa.DateTime(), nullable=True),
    sa.Column('date_of_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
