"""fixed sessions model

Revision ID: 52477ebf577b
Revises: 47380682aa83
Create Date: 2024-05-24 12:25:19.629053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52477ebf577b'
down_revision = '47380682aa83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_number', sa.String(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('session_number')

    # ### end Alembic commands ###
