"""fix invite name

Revision ID: a5751d7d34f5
Revises: cc5dcef93945
Create Date: 2024-05-29 22:44:41.226577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5751d7d34f5'
down_revision = 'cc5dcef93945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_invite', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_of_invate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_invate', sa.DATETIME(), nullable=True))
        batch_op.drop_column('date_of_invite')

    # ### end Alembic commands ###
