"""add Message Model

Revision ID: cc5dcef93945
Revises: 4037b1420e0c
Create Date: 2024-05-29 22:12:34.951137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5dcef93945'
down_revision = '4037b1420e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('date_and_hour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['friends_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
